pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD', '~> 2.0-beta4'
pod 'FMDB', '~> 2.6'
pod 'SDWebImage-Category', '~> 1.4'
pod 'AFNetworking+ImageActivityIndicator', '~> 1.0.2'
pod 'SDCycleScrollView', '~> 1.6'

